name: pola_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 3.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2+2
  chopper: ^8.0.1+1
  http: ^1.2.1
  equatable: ^2.0.7
  json_annotation: any
  logger: ^2.3.0
  rxdart: ^0.28.0
  mobile_scanner: ^6.0.11
  in_app_review: ^2.0.2
  uuid: ^4.4.0
  shared_preferences: ^2.0.6
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.4
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  url_launcher: ^6.3.2
  url_launcher_ios: ^6.3.2
  vibration: ^3.1.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  slang: ^4.7.2
  slang_flutter: ^4.10.0
  syncfusion_flutter_gauges: ^29.2.7
  flutter_svg: ^2.0.9
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  flutter_gen_runner: ^5.6.0
  json_serializable: any
  chopper_generator: ^8.0.1
  test: any
  bloc_test: ^9.1.7
  mockito:  ^5.0.0-nullsafety.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/menuPage/
    - assets/fonts/
    - assets/company/
    - assets/navigation/
    - assets/scan/
    - assets/tabs/

  fonts:
    - family: Roboto 
      fonts: 
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Lato 
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700 
        - asset: assets/fonts/Lato/Lato-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/theme/
  line_length: 120 

  integrations:
    flutter_svg: true
